### ISSUE TITLE
features for string.py

### ISSUE THREAD

**Issue by MechHedgehog** [MechHedgehog/Final_project#3]
1) Add messages log (like chat with yourself), may be with "send time"
2) Add copying text on enter button, after pressing "message" appears in log, input line becomes clear
3) Add fast hotkey combination for adding predicted  words (like ctrl+1 or so on)
4) Add somewhere in corner button "upgrade dict" with no event now, i'll code it soon
5) May be add some decoration like changing font, background, all, that you can imagine and code

**Comment by PrusakovMS** [comment]
Features are added^^:
Enter is copying text button now
The predicted words can be added to the text by pushing "1", "2" or "3" button.
F5 may be now used for updating predicted words

**Comment by MechHedgehog** [comment]
Change adding words from "1", "2", '"3" to F1 or ctrl + 1, because if someone want to write 123 he'll get приветкакдела instead.

**Comment by PrusakovMS** [comment]
The problem is solved) For adding predicted words you should now push ctrl+1, 2, 3 button.
